#!/bin/bash
#SBATCH -t 05:00:00
#SBATCH --reservation=rumc_lab
#SBATCH -N 1 -c 32
#SBATCH -p broadwell
module load python/3.5.2
pip uninstall tensorflow
pip install https://storage.googleapis.com/intel-optimized-tensorflow/tensorflow-1.11.0-cp35-cp35m-linux_x86_64.whl --user
pip install keras --user
pip install tqdm --user
pip install requests --user
pip install Pillow --user
pip install scikit-image --user
module load gcc/4.9.2

ssh -o StrictHostKeyChecking=no -f -N -p 22 -R YOUR_PORT_NUMBER:localhost:YOUR_PORT_NUMBER int3
jupyter notebook --no-browser --port YOUR_PORT_NUMBER
