#!/bin/bash
#SBATCH -t 03:00:00
#SBATCH -N 1 -c 32
#SBATCH -p broadwell
module load python/3.5.2
pip uninstall tensorflow
pip install https://storage.googleapis.com/intel-optimized-tensorflow/tensorflow-1.11.0-cp35-cp35m-linux_x86_64.whl --user
pip install keras --user
pip install tqdm --user
pip install requests --user
pip install Pillow --user
module load gcc/4.9.2

ssh -o StrictHostKeyChecking=no -f -N -p 22 -R 5106:localhost:5106 int3
jupyter notebook --no-browser --port 5106
